version: "3"

services:
  mariadb:
    image: mariadb:latest
    restart: 'unless-stopped'
    container_name: fabiancdng-com-db
    volumes:
      - './docker-volumes/mariadb:/var/lib/mysql'
    environment:
      MYSQL_ROOT_PASSWORD: 'tester'
      MYSQL_DATABASE: 'strapi'
      MYSQL_USER: 'strapi'
      MYSQL_PASSWORD: 'tester'

  cms:
    image: fabiancdng-com-cms
    container_name: fabiancdng-com-cms
    restart: unless-stopped
    env_file:
      - ./cms/.env
    volumes:
      - './cms/database:/app/database'
      - './cms/public:/app/public'
    depends_on:
      - mariadb
    ports:
      - "1337:1337"
    
  frontend:
    image: fabiancdng-com-frontend
    container_name: fabiancdng-com-frontend
    restart: unless-stopped
    depends_on:
      - cms
    ports:
      - "3000:3000"