version: '3'

services:
  fabiancdng-website:
    image: ghcr.io/fabiancdng/fabiancdng-website:latest
    container_name: fabiancdng-website
    restart: unless-stopped
    ports:
      - '3000:3000'
