name: Build and push Docker image of front end

on:
  push:
    tags:
      - '*'

jobs:
  next-build:
    runs-on: ubuntu-latest
    name: Build and Deploy Next.js App
    steps:
      - name: Checkout code
        uses: actions/checkout@v1
        # Make sure submodules are cloned too.
        # Submodule is private, so we need to use an access token.
        with:
          submodules: true
          token: ${{ secrets.WEBSITE_BUILD_AT }}
      - name: Build the Next.js app
        env:
          NEXT_PUBLIC_DOMAIN: ${{ vars.NEXT_PUBLIC_DOMAIN }}
          NEXT_PUBLIC_CONTACT_EMAIL: ${{ vars.NEXT_PUBLIC_CONTACT_EMAIL }}
        run: npm install && npm run build
      - name: Login to GitHub Container Registry (ghcr.io)
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and push Docker image
        uses: docker/build-push-action@v2
        with:
          context: .
          push: true
          tags: |
            ghcr.io/fabiancdng/fabiancdng-website:latest
